resource_types:
  - name: bitbucket-build-status
    type: docker-image
    source:
      repository: shyxormz/bitbucket-build-status-resource
  - name: artifactory-resource
    type: docker-image
    source:
      repository: springio/artifactory-resource
      tag: 0.0.10
resources:
  - name: repo
    type: git
    source:
      uri: https://bitbucket.1and1.org/scm/acc-dbo/pg-exporter.git
      branch: master
      skip_ssl_verification: true

  - name: build-status
    type: bitbucket-build-status
    source:
      username: tberger
      password: ((bitbucket-password))
      endpoint: https://bitbucket.1and1.org
      verify_ssl: false
      repository: acc-dbo/pg-exporter

  - name: artifacts
    type: artifactory-resource
    source:
      uri: https://artifactory.1and1.org/artifactory
      username: paccdboci
      password: ((artifactory-key))
      build_name: pg-exporter

jobs:
  - name: build
    public: true
    plan:
    - get: repo
      trigger: true
    - put: build-status
      params:
        build_status: INPROGRESS
        repository: repo
    - task: run-build
      file: repo/tasks/build.yml
      on_success:
        put: build-status
        params:
          build_status: SUCCESSFUL
          repository: repo
      on_failure:
        put: build-status
        params:
          build_status: FAILED
          repository: repo
    - put: artifacts
      params:
        repo: accdbo-go
        build_number: "pgexporter-${BUILD_ID}"
        module_layout: none
        build_uri: ${ATC_EXTERNAL_URL}/teams/${BUILD_TEAM_NAME}/jobs/${BUILD_JOB_NAME}
        folder: binaries
        include:
          - "*"