/*generated by binding gen*/
package models

import (
	"github.com/prometheus/client_golang/prometheus"
)

func (r *PgStatIo) ToMetrics(namespace string, subsystem string, ch chan<- prometheus.Metric, labelsKV ...string) error {
	labels := newLabels(labelsKV...)
	// labels
	labels["backend_type"] = r.BackendType
	labels["object"] = r.Object
	labels["context"] = r.Context

	// optional labels

	// metrics
	// statio_reads_total (CounterValue)
	statioReadsTotal := float64(r.Reads)
	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `statio_reads_total`), `Number of read operations`, nil, labels,
		), prometheus.CounterValue, statioReadsTotal,
	)

	// statio_read_time (CounterValue)

	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `statio_read_time`), `Time spent waiting for read operations in milliseconds`, nil, labels,
		), prometheus.CounterValue, r.ReadTime,
	)

	// statio_writes_total (CounterValue)
	statioWritesTotal := float64(r.Writes)
	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `statio_writes_total`), `Number of write operations`, nil, labels,
		), prometheus.CounterValue, statioWritesTotal,
	)

	// statio_write_time (CounterValue)

	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `statio_write_time`), `Time spent waiting for write operations in milliseconds`, nil, labels,
		), prometheus.CounterValue, r.WriteTimes,
	)

	// statio_writebacks_total (CounterValue)
	statioWritebacksTotal := float64(r.WriteBacks)
	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `statio_writebacks_total`), `Number of units of size BLCKSZ (typically 8kB) which the process requested the kernel write out to permanent storage`, nil, labels,
		), prometheus.CounterValue, statioWritebacksTotal,
	)

	// statio_writeback_time (CounterValue)

	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `statio_writeback_time`), `Time spent waiting for writeback operations in milliseconds (if track_io_timing is enabled, otherwise zero). This includes the time spent queueing write-out requests and, potentially, the time spent to write out the dirty data`, nil, labels,
		), prometheus.CounterValue, r.WriteBackTime,
	)

	// statio_extends_total (CounterValue)
	statioExtendsTotal := float64(r.Extends)
	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `statio_extends_total`), `Number of relation extend operations`, nil, labels,
		), prometheus.CounterValue, statioExtendsTotal,
	)

	// statio_extend_time (CounterValue)

	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `statio_extend_time`), `Time spent waiting for extend operations in milliseconds. (if track_io_timing is enabled and object is not wal, or if track_wal_io_timing is enabled and object is wal, otherwise zero)`, nil, labels,
		), prometheus.CounterValue, r.ExtendTime,
	)

	// statio_hits_total (CounterValue)
	statioHitsTotal := float64(r.Hits)
	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `statio_hits_total`), `The number of times a desired block was found in a shared buffer`, nil, labels,
		), prometheus.CounterValue, statioHitsTotal,
	)

	// evictions (CounterValue)
	evictions := float64(r.Evictions)
	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `evictions`), `Number of times a block has been written out from a shared or local buffer in order to make it available for another use`, nil, labels,
		), prometheus.CounterValue, evictions,
	)

	// statio_reuses_total (CounterValue)
	statioReusesTotal := float64(r.Reuses)
	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `statio_reuses_total`), `The number of times an existing buffer in a size-limited ring buffer outside of shared buffers was reused as part of an I/O operation in the bulkread, bulkwrite, or vacuum contexts`, nil, labels,
		), prometheus.CounterValue, statioReusesTotal,
	)

	// statio_fsyncs_total (CounterValue)
	statioFsyncsTotal := float64(r.Fsyncs)
	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `statio_fsyncs_total`), `Number of fsync calls. These are only tracked in context normal`, nil, labels,
		), prometheus.CounterValue, statioFsyncsTotal,
	)

	// statio_fsync_time (CounterValue)

	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `statio_fsync_time`), `Time spent waiting for fsync operations in milliseconds`, nil, labels,
		), prometheus.CounterValue, r.FsyncTime,
	)

	// stats_reset (CounterValue)
	var statsReset float64
	if r.StatsReset.IsZero() {
		statsReset = float64(0)
	} else {
		statsReset = float64(r.StatsReset.Unix())
	}
	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `stats_reset`), `Time at which these statistics were last reset`, nil, labels,
		), prometheus.CounterValue, statsReset,
	)

	// optional metrics
	// statio_op_bytes_total (CounterValue)
	if r.OpBytes.Valid {
		statioOpBytesTotal := float64(r.OpBytes.Int64)

		ch <- prometheus.MustNewConstMetric(
			prometheus.NewDesc(
				prometheus.BuildFQName(namespace, subsystem, `statio_op_bytes_total`), `The number of bytes per unit of I/O read, written, or extended`, nil, labels,
			), prometheus.CounterValue, statioOpBytesTotal,
		)
	}
	// statio_read_bytes_total (CounterValue)
	if r.ReadBytes.Valid {
		statioReadBytesTotal := r.ReadBytes.Float64

		ch <- prometheus.MustNewConstMetric(
			prometheus.NewDesc(
				prometheus.BuildFQName(namespace, subsystem, `statio_read_bytes_total`), `The total size of read operations in bytes`, nil, labels,
			), prometheus.CounterValue, statioReadBytesTotal,
		)
	}
	// statio_write_bytes_total (CounterValue)
	if r.WriteBytes.Valid {
		statioWriteBytesTotal := r.WriteBytes.Float64

		ch <- prometheus.MustNewConstMetric(
			prometheus.NewDesc(
				prometheus.BuildFQName(namespace, subsystem, `statio_write_bytes_total`), `The total size of write operations in bytes`, nil, labels,
			), prometheus.CounterValue, statioWriteBytesTotal,
		)
	}
	// statio_extend_bytes_total (CounterValue)
	if r.ExtendBytes.Valid {
		statioExtendBytesTotal := r.ExtendBytes.Float64

		ch <- prometheus.MustNewConstMetric(
			prometheus.NewDesc(
				prometheus.BuildFQName(namespace, subsystem, `statio_extend_bytes_total`), `The total size of relation extend operations in bytes`, nil, labels,
			), prometheus.CounterValue, statioExtendBytesTotal,
		)
	}

	return nil
}
