/*generated by binding gen*/
package models

import (
	"github.com/prometheus/client_golang/prometheus"
)

func (r *PgStatBgWriter17) ToMetrics(namespace string, subsystem string, ch chan<- prometheus.Metric, labelsKV ...string) error {
	labels := newLabels(labelsKV...)
	// labels

	// optional labels

	// metrics
	// buffers_clean_total (CounterValue)
	buffersCleanTotal := float64(r.BuffersClean)
	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `buffers_clean_total`), `Number of buffers written by the background writer`, nil, labels,
		), prometheus.CounterValue, buffersCleanTotal,
	)

	// maxwritten_clean_total (CounterValue)
	maxwrittenCleanTotal := float64(r.MaxwrittenClean)
	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `maxwritten_clean_total`), `Number of times the background writer stopped a cleaning scan because it had written too many buffers`, nil, labels,
		), prometheus.CounterValue, maxwrittenCleanTotal,
	)

	// buffers_alloc_total (CounterValue)
	buffersAllocTotal := float64(r.BuffersAlloc)
	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `buffers_alloc_total`), `Number of buffers allocated`, nil, labels,
		), prometheus.CounterValue, buffersAllocTotal,
	)

	// stats_reset (CounterValue)
	var statsReset float64
	if r.StatsReset.IsZero() {
		statsReset = float64(0)
	} else {
		statsReset = float64(r.StatsReset.Unix())
	}
	ch <- prometheus.MustNewConstMetric(
		prometheus.NewDesc(
			prometheus.BuildFQName(namespace, subsystem, `stats_reset`), `Time at which these statistics were last reset`, nil, labels,
		), prometheus.CounterValue, statsReset,
	)

	// optional metrics

	return nil
}
