/*generated by binding gen*/
package models

import (
	"github.com/prometheus/client_golang/prometheus"
)

func (r *PgTxid) ToMetrics(namespace string, subsystem string, ch chan<- prometheus.Metric, labelsKV ...string) error {
	labels := newLabels(labelsKV...)
	// labels

	// optional labels

	// metrics

	// optional metrics
	// current (CounterValue)
	if r.Current.Valid {
		current := float64(r.Current.Int64)

		ch <- prometheus.MustNewConstMetric(
			prometheus.NewDesc(
				prometheus.BuildFQName(namespace, subsystem, `current`), `The current transaction ID on the database cluster`, nil, labels,
			), prometheus.CounterValue, current,
		)
	}

	return nil
}
